version: '3.8'

services:
  api:
    build:
      context: ./ScheduleAPI
      dockerfile: Dockerfile
    ports:
      - "5566:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Development}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data: 