services:
  api:
    build:
      context: ./ScheduleAPI
      dockerfile: Dockerfile
    ports:
      - "5566:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Development}
      - ConnectionStrings__Redis=${ENVIRONMENT:-Development}-redis:6379
      - ConnectionStrings__RabbitMQ=${ENVIRONMENT:-Development}-rabbitmq:5672
    depends_on:
      - ${ENVIRONMENT:-Development}-redis
      - ${ENVIRONMENT:-Development}-rabbitmq
    networks:
      - app-network

  # 開發環境使用的 Redis
  Development-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    profiles:
      - dev

  # 生產環境的空 Redis 服務
  Production-redis:
    image: alpine:latest
    command: echo "Redis 服務在生產環境中不啟動"
    profiles:
      - prod

  # 條件性服務：僅在生產環境中啟動 RabbitMQ
  Production-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    profiles:
      - prod

  # 空服務，在開發環境中替代 RabbitMQ
  Development-rabbitmq:
    image: alpine:latest
    command: echo "RabbitMQ 服務在開發環境中不啟動"
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data: 